package conda

import (
	"crypto/sha256"
	"slices"
	"strings"
	"testing"
)

// Real `micromamba env export --explicit --no-md5` output, generated header and
// all.
const explicitExport = `# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/python-3.12.5-h2ad013b_0_cpython.conda
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-hda65f42_9.conda
https://conda.anaconda.org/conda-forge/linux-64/_go_select-2.3.0-cgo.tar.bz2
`

func TestCanonicalExplicit(t *testing.T) {
	got, err := CanonicalExplicit([]byte(explicitExport))
	if err != nil {
		t.Fatalf("CanonicalExplicit: %v", err)
	}
	want := strings.Join([]string{
		"@EXPLICIT",
		"https://conda.anaconda.org/conda-forge/linux-64/_go_select-2.3.0-cgo.tar.bz2",
		"https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-hda65f42_9.conda",
		"https://conda.anaconda.org/conda-forge/linux-64/python-3.12.5-h2ad013b_0_cpython.conda",
		"",
	}, "\n")
	if string(got) != want {
		t.Errorf("canonical explicit:\n%s\nwant:\n%s", got, want)
	}
}

// The whole reason for re-emitting: a Micromamba upgrade that reorders or
// re-spaces its output must not move the key of every artifact built after it.
func TestCanonicalExplicitIsStableAcrossExporters(t *testing.T) {
	reordered := `# generated by a different micromamba
@EXPLICIT

https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-hda65f42_9.conda#0f6f2e4e0e1c3a9e
   https://conda.anaconda.org/conda-forge/linux-64/_go_select-2.3.0-cgo.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-3.12.5-h2ad013b_0_cpython.conda
`
	first, err := CanonicalExplicit([]byte(explicitExport))
	if err != nil {
		t.Fatal(err)
	}
	second, err := CanonicalExplicit([]byte(reordered))
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Errorf("two exporters of one solve disagreed:\n%s\nvs\n%s", first, second)
	}
	// An md5 suffix is a checksum of the download, not of what was installed.
	if strings.Contains(string(second), "#") {
		t.Errorf("an md5 suffix survived:\n%s", second)
	}
	// The identity is the digest of these exact bytes.
	if sha256.Sum256(first) != sha256.Sum256(second) {
		t.Error("identical content hashed differently")
	}
}

func TestCanonicalExplicitRejectsNonExplicit(t *testing.T) {
	if _, err := CanonicalExplicit([]byte("name: env\ndependencies:\n  - python\n")); err == nil {
		t.Error("an environment.yml was accepted as an explicit spec")
	}
}

const environmentExportYAML = `name: cutadapt-5.0
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12.5
  - bzip2=1.0.8
  - pip:
      - some-wheel==1.2.3
      - another==0.1
prefix: /tmp/build/cnt/cutadapt/5.0
`

func TestCanonicalEnvironment(t *testing.T) {
	got, err := CanonicalEnvironment([]byte(environmentExportYAML), []string{"conda-forge", "bioconda"})
	if err != nil {
		t.Fatalf("CanonicalEnvironment: %v", err)
	}
	want := strings.Join([]string{
		"channels:",
		"  - conda-forge",
		"  - bioconda",
		"dependencies:",
		"  - bzip2=1.0.8",
		"  - python=3.12.5",
		"  - pip:",
		"      - another==0.1",
		"      - some-wheel==1.2.3",
		"",
	}, "\n")
	if string(got) != want {
		t.Errorf("canonical environment:\n%s\nwant:\n%s", got, want)
	}
	// name and prefix describe a temporary local environment, not its packages.
	for _, dropped := range []string{"name:", "prefix:", "cutadapt-5.0", "/tmp/build"} {
		if strings.Contains(string(got), dropped) {
			t.Errorf("%q survived into the canonical environment:\n%s", dropped, got)
		}
	}
}

// Adding a channel to a site's config must change no artifact's key, so only
// channels that actually provided a package may reach the file.
func TestCanonicalEnvironmentTakesTheChannelSetFromTheExport(t *testing.T) {
	export := "channels:\n  - conda-forge\ndependencies:\n  - python=3.12.5\n"

	narrow, err := CanonicalEnvironment([]byte(export), []string{"conda-forge"})
	if err != nil {
		t.Fatal(err)
	}
	wide, err := CanonicalEnvironment([]byte(export), []string{"conda-forge", "bioconda", "nvidia"})
	if err != nil {
		t.Fatal(err)
	}
	if string(narrow) != string(wide) {
		t.Errorf("configuring an unused channel changed the file:\n%s\nvs\n%s", narrow, wide)
	}
	if strings.Contains(string(wide), "bioconda") {
		t.Errorf("a channel that provided nothing was recorded:\n%s", wide)
	}
}

func TestOrderChannels(t *testing.T) {
	tests := []struct {
		name     string
		exported []string
		priority []string
		want     []string
	}{
		{
			name:     "exporter order is alphabetical, not solve order",
			exported: []string{"bioconda", "conda-forge"},
			priority: []string{"conda-forge", "bioconda"},
			want:     []string{"conda-forge", "bioconda"},
		},
		{
			name:     "a configured channel that provided nothing is left out",
			exported: []string{"conda-forge"},
			priority: []string{"conda-forge", "bioconda"},
			want:     []string{"conda-forge"},
		},
		{
			name:     "an unconfigured channel is appended, sorted, never dropped",
			exported: []string{"nvidia", "conda-forge", "my-mirror"},
			priority: []string{"conda-forge"},
			want:     []string{"conda-forge", "my-mirror", "nvidia"},
		},
		{
			name:     "no priority at all still yields a total order",
			exported: []string{"bioconda", "conda-forge"},
			priority: nil,
			want:     []string{"bioconda", "conda-forge"},
		},
		{
			name:     "duplicates collapse",
			exported: []string{"conda-forge", "conda-forge"},
			priority: []string{"conda-forge"},
			want:     []string{"conda-forge"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := OrderChannels(tt.exported, tt.priority); !slices.Equal(got, tt.want) {
				t.Errorf("OrderChannels(%v, %v) = %v, want %v", tt.exported, tt.priority, got, tt.want)
			}
		})
	}
}

// Identity moves on a build string, equivalence does not; a version moves both.
// That asymmetry is the whole reason two exports are captured.
func TestBuildStringsSeparateTheTwoExports(t *testing.T) {
	rebuild := strings.Replace(explicitExport, "bzip2-1.0.8-hda65f42_9", "bzip2-1.0.8-h4bc722e_7", 1)
	if rebuild == explicitExport {
		t.Fatal("the fixture did not change")
	}
	a, _ := CanonicalExplicit([]byte(explicitExport))
	b, _ := CanonicalExplicit([]byte(rebuild))
	if string(a) == string(b) {
		t.Error("a changed build string did not move the identity preimage")
	}

	// The environment export never carried the build string in the first place.
	env := "channels:\n  - conda-forge\ndependencies:\n  - bzip2=1.0.8\n"
	c, _ := CanonicalEnvironment([]byte(env), []string{"conda-forge"})
	d, _ := CanonicalEnvironment([]byte(env), []string{"conda-forge"})
	if string(c) != string(d) {
		t.Error("the equivalence preimage is not stable")
	}
}
